name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches_ignore: []

jobs:
  Dry_Run_and_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Dry Run with test data, all options
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/chicyte cite --genome hg38 --input \
        /opt2/.tests/WT_S1.R1.fastq.gz /opt2/.tests/WT_S1.R2.fastq.gz \
        /opt2/.tests/WT_S2_R1.fastq.gz /opt2/.tests/WT_S2_R2.fastq.gz \
        /opt2/.tests/WT_S3_1.fastq.gz /opt2/.tests/WT_S3_2.fastq.gz \
        /opt2/.tests/WT_S4_R1.001.fastq.gz /opt2/.tests/WT_S4_R2.001.fastq.gz \
        --libraries /opt2/.tests/libraries.csv --features /opt2/.tests/features.csv \
        --num-cells 4000  --force-cells --pre-mrna --output /opt2/output --mode local --dry-run
    - name: Dry Run with test data, use defaults
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/chicyte cite --genome hg38 --input \
        /opt2/.tests/WT_S1.R1.fastq.gz /opt2/.tests/WT_S1.R2.fastq.gz \
        /opt2/.tests/WT_S2_R1.fastq.gz /opt2/.tests/WT_S2_R2.fastq.gz \
        /opt2/.tests/WT_S3_1.fastq.gz /opt2/.tests/WT_S3_2.fastq.gz \
        /opt2/.tests/WT_S4_R1.001.fastq.gz /opt2/.tests/WT_S4_R2.001.fastq.gz \
        --libraries /opt2/.tests/libraries.csv --features /opt2/.tests/features.csv \
        --output /opt2/output --mode local --dry-run
    - name: Lint Workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
